/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 68c1f8176b4f4b35351a80df3b685f4f)
interface __BaseEnv_Env {
  TASK_RUNNER: DurableObjectNamespace<import("./src/index").TaskRunner>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "TaskRunner";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
