/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: ddd08ff55fe84b0023ebe5c63bf6de17)
interface __BaseEnv_Env {
  REPORT_API_URL: "https://report-api.example.com";
  TASK_RUNNER: DurableObjectNamespace<import("./src/index").TaskRunner>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "TaskRunner";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "REPORT_API_URL">> {}
}
