/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=test/fixtures/wrangler.jsonc --include-runtime=false test/fixtures/env.d.ts` (hash: f27a033a0392b85d2b31e63cac3343df)
interface __BaseEnv_Env {
  TASK_RUNNER: DurableObjectNamespace<import("./worker").TaskRunner>;
  TASK_RUNNER_REAL: DurableObjectNamespace<import("./worker").RealTaskRunner>;
  TASK_RUNNER_LIB: DurableObjectNamespace<import("./worker").LibraryTaskRunner>;
  TASK_EXECUTOR: Service<typeof import("./worker").TaskExecutor>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./worker");
    durableNamespaces: "TaskRunner" | "RealTaskRunner" | "LibraryTaskRunner";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
